import Head from "next/head";
import { useState } from "react";
import HorizontalCsl from '../components/HorizontalCsl.jsx'

import CardCarousel from "../components/CardCarousel";
import FilterSort from "../components/FilterSort";
import Loader from "../components/Loader";
import ProductItem from "../components/ProductItem";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isLoading, setisLoading] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Violet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <HorizontalCsl/>
      <FilterSort />
      <div className={styles.home_container_product}>
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
        <ProductItem />
      </div>
      {isLoading ? <Loader /> : null}
    </div>
  );
}
